# Generated by Django 5.0.6 on 2024-06-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_build_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
