# Generated by Django 5.0.6 on 2024-06-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
