# Generated by Django 5.0.6 on 2024-06-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_alter_build_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='build_type',
            field=models.CharField(choices=[('Designed By Lego', 'Designed By Lego'), ('Self Made', 'Self Made')], default='Designed By Lego', max_length=50),
        ),
    ]
