# Generated by Django 5.0.6 on 2024-06-26 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_review_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='builds.build'),
        ),
    ]
